[pytest]
markers =
    smoke: быстрые тесты
    critical: критические тесты
    regression: регрессионные тесты
    slow: медленные тесты
    api: API-тесты
    ui: UI-тесты
    fluky: Нестабильные тесты
    positive: позитивные тесты
    negative: негативные тесты
    db_check: тесты с включенной сверкой изменений в БД
    rbac: тесты прав доступа

    user: тесты по работе с аккаунтами
    review: тесты по работе с отзывами
    payment: тесты оплаты
    movies: тесты работы с фильмами

log_cli = 1
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format=%Y-%m-%d %H:%M:%S

#log_cli_format = "%(asctime)s.%(msecs)03d %(message)s"

