name: Run Tests and Generate Report

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      API_SUPERADMIN_EMAIL: ${{ secrets.API_SUPERADMIN_EMAIL }}
      API_SUPERADMIN_PASSWORD: ${{ secrets.API_SUPERADMIN_PASSWORD }}
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/ms-playwright

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install allure-pytest pytest-playwright
          playwright install --with-deps

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          ALLURE_VERSION=2.24.0
          wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz
          tar -zxvf allure-${ALLURE_VERSION}.tgz
          sudo mv allure-${ALLURE_VERSION} /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Run tests (без БД)
        run: pytest -m "not db_check" --alluredir=allure-results

      - name: Generate report
        run: allure generate allure-results -o allure-report --clean

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report